Repository atos-df-rennes/prevarisc-passerelle-platau, pull requests merged in 2024-07, with the labels that each got.

#16 Prise en compte des documents manquants en tant qu'observations
  src/Command/ExportPEC.php
  src/Service/Prevarisc.php
Labels: enhancement

#17 Ne réimporte pas la pièce si elle existe avec l'ancien nommage
  src/Service/Prevarisc.php
Labels: bug

#18 Intégration de GitHub Actions
  .github/workflows/actions.yml
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml
  src/Command/ExportPEC.php
  src/Service/PlatauCollection.php
  src/Service/Prevarisc.php
Labels: enhancement

#20 feat: scripts composer
  composer.json
Labels: enhancement

#19 chore: mise à jour des paquets
  composer.lock
  psalm-baseline.xml
  src/Service/Prevarisc.php
Labels: dependencies

#21 feat!: passage sur la version 11 de l'API Plat'AU
  src/Command/Healthcheck.php
  src/Service/PlatauAbstract.php
Labels: enhancement
